spring:
  application:
    name: cloudbalance
  datasource:
    url: jdbc:mysql://localhost:3306/cloudbalance
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: SameerKhanIsAFullStackDeveloperAtCloudKeeper
  expiration: 7200000

snowflake:
  url: https://nwbzkah-gk39699.snowflakecomputing.com
  username: SAMIRKHAN
  password: Technology@2021
  warehouse: COMPUTE_WH
  database: CLOUDBALANCE
  schema: PUBLIC
  role : ACCOUNTADMIN